remote_theme: sighingnow/jekyll-gitbook
title: 龙芯班手册
auther: Vincent-ice
description: 龙芯班的一些教程
syntax_highlighter_style: colorful

url: "https://vincent-ice.github.io"
baseurl: "/loongson-github-pages"

# permalink: ':title:output_ext'

toc:
    enabled: true
    h_min: 1
    h_max: 3
